<?php

return [
    'PESAPAL_ENVIRONMENT' => env('PESAPAL_ENVIRONMENT'),
    'PESAPAL_CONSUMER_KEY' => env('PESAPAL_CONSUMER_KEY'),
    'PESAPAL_CONSUMER_SECRET' => env('PESAPAL_CONSUMER_SECRET'),
    'PESAPAL_CALLBACK_URL' => env('PESAPAL_CALLBACK_URL'),
];
