export const expenseCategories = [
    { value: "rent", label: "Rent" },
    { value: "mortgage", label: "Mortgage" },
    { value: "utilities", label: "Utilities" },
    { value: "groceries", label: "Groceries" },
    { value: "transportation", label: "Transportation" },
    { value: "fuel", label: "Fuel" },
    { value: "insurance", label: "Insurance" },
    { value: "healthcare", label: "Healthcare" },
    { value: "subscriptions", label: "Subscriptions" },
    { value: "entertainment", label: "Entertainment" },
    { value: "dining_out", label: "Dining Out" },
    { value: "education", label: "Education" },
    { value: "childcare", label: "Childcare" },
    { value: "loan_payment", label: "Loan Payment" },
    { value: "credit_card_payment", label: "Credit Card Payment" },
    { value: "savings", label: "Savings" },
    { value: "investments", label: "Investments" },
    { value: "charity", label: "Charity" },
    { value: "clothing", label: "Clothing" },
    { value: "pet_expenses", label: "Pet Expenses" },
    { value: "vacation", label: "Vacation" },
    { value: "home_maintenance", label: "Home Maintenance" },
    { value: "phone_bill", label: "Phone Bill" },
    { value: "internet", label: "Internet" },
    { value: "gym_membership", label: "Gym Membership" },
    { value: "gifts", label: "Gifts" },
    { value: "taxes", label: "Taxes" },
    { value: "other", label: "Other" },
];
