export const goalTypes = [
    { value: "emergency_fund", label: "Emergency Fund" },
    { value: "school_fees", label: "School Fees" },
    { value: "business_startup", label: "Start a Business" },
    { value: "home_construction", label: "Build a Home" },
    { value: "home_purchase", label: "Buy a Home" },
    { value: "vehicle_purchase", label: "Buy a Vehicle" },
    { value: "travel", label: "Travel / Vacation" },
    { value: "wedding", label: "Wedding" },
    { value: "medical_expenses", label: "Medical Expenses" },
    { value: "debt_repayment", label: "Debt Repayment" },
    { value: "retirement", label: "Retirement Savings" },
    { value: "education", label: "Further Education" },
    { value: "electronics", label: "Buy Electronics" },
    { value: "furniture", label: "Buy Furniture" },
    { value: "other", label: "Other" },
];
