export const incomeCategories = [
    { value: "salary", label: "Salary" },
    { value: "freelance", label: "Freelance" },
    { value: "business_income", label: "Business Income" },
    { value: "rental_income", label: "Rental Income" },
    { value: "investments", label: "Investments" },
    { value: "dividends", label: "Dividends" },
    { value: "interest", label: "Interest" },
    { value: "pension", label: "Pension" },
    { value: "government_benefits", label: "Government Benefits" },
    { value: "alimony", label: "Alimony" },
    { value: "child_support", label: "Child Support" },
    { value: "lottery_winnings", label: "Lottery Winnings" },
    { value: "side_hustle", label: "Side Hustle" },
    { value: "gift", label: "Gift" },
    { value: "inheritance", label: "Inheritance" },
    { value: "scholarship", label: "Scholarship" },
    { value: "bonus", label: "Bonus" },
    { value: "royalties", label: "Royalties" },
    { value: "other", label: "Other" },
];
