export const moneyMarketFunds = [
    { value: "cytonn_mmf", label: "Cytonn Money Market Fund", return: "11.85" },

    {
        value: "gulfcap_mmf",
        label: "Gulfcap Money Market Fund",
        return: "10.79",
    },
    { value: "ndovu_mmf", label: "Ndovu Money Market Fund", return: "11.05" },
    {
        value: "lotry_corban_mmf",
        label: "Lotry-Corban Money Market Fund",
        return: "11.07",
    },
    { value: "kuza_mmf", label: "Kuza Money Market Fund", return: "10.62" },
    { value: "etica_mmf", label: "Etica Money Market Fund", return: "11.59" },
    {
        value: "nabo_africa_mmf",
        label: "Nabo Africa Money Market Fund",
        return: "11.62",
    },
    {
        value: "genafrica_mmf",
        label: "GenAfrica Money Market Fund",
        return: "9.48",
    },
    {
        value: "british_american_mmf",
        label: "British-American Money Market Fund",
        return: "10.40",
    },
    {
        value: "old_mutual_mmf",
        label: "Old Mutual Money Market Fund",
        return: "10.59",
    },
    {
        value: "orient_kasha_mmf",
        label: "Orient Kasha Money Market Fund",
        return: "10.67",
    },
    {
        value: "madison_mmf",
        label: "Madison Money Market Fund",
        return: "10.00",
    },
    {
        value: "arvocaap_mmf",
        label: "Arvocaap Money Market Fund",
        return: "11.95",
    },
    {
        value: "enwealth_mmf",
        label: "Enwealth Money Market Fund",
        return: "11.07",
    },
    {
        value: "jubilee_mmf",
        label: "Jubilee Money Market Fund",
        return: "10.67",
    },
    { value: "apollo_mmf", label: "Apollo Money Market Fund", return: "9.49" },
    { value: "faulu_mmf", label: "Faulu Money Market Fund", return: "9.38" },
    { value: "sanlam_mmf", label: "Sanlam Money Market Fund", return: "9.44" },
    {
        value: "dry_associates_mmf",
        label: "Dry Associates Money Market Fund",
        return: "9.79",
    },
    { value: "kcb_mmf", label: "KCB Money Market Fund", return: "9.00" },
    { value: "maai_mmf", label: "Maai Money Market Fund", return: "8.22" },
    { value: "co_op_mmf", label: "Co-op Money Market Fund", return: "8.12" },
    {
        value: "icea_lion_mmf",
        label: "ICEA Lion Money Market Fund",
        return: "8.60",
    },
    {
        value: "genghis_mmf",
        label: "Genghis Money Market Fund",
        return: "8.49",
    },
    {
        value: "mayfair_mmf",
        label: "Mayfair Money Market Fund",
        return: "7.68",
    },
    { value: "cic_mmf", label: "CIC Money Market Fund", return: "8.53" },
    {
        value: "absa_shilling_mmf",
        label: "Absa Shilling Money Market Fund",
        return: "7.66",
    },
    { value: "cpf_mmf", label: "CPF Money Market Fund", return: "8.46" },
    { value: "aa_kenya_mmf", label: "AA Kenya Shilling Fund", return: "6.58" },
    { value: "zidi_mmf", label: "Zidi Money Market Fund", return: "6.51" },
    {
        value: "stanbic_mmf",
        label: "Stanbic Money Market Fund",
        return: "6.07",
    },
    { value: "equity_mmf", label: "Equity Money Market Fund", return: "5.02" },
];

export const bonds = [
    {
        value: "infrastructure_bond",
        label: "Infrastructure Bond",
        return: "14.0",
    },
    { value: "government_bond", label: "Government Bond", return: "13.5" },
    { value: "corporate_bond", label: "Corporate Bond", return: "12.0" },
];

export const realEstate = [
    { value: "residential", label: "Residential" },
    { value: "commercial", label: "Commercial" },
    { value: "land", label: "Land" },
    { value: "reits", label: "Reits" },
];

export const treasuryBills = [
    {
        value: "t_bill_91",
        label: "91-Day Treasury Bill",
        return: "8.2816",
        issue_number: "2634/091",
        auction_date: "12/06/2025",
        value_dated: "16/06/2025",
    },
    {
        value: "t_bill_182",
        label: "182-Day Treasury Bill",
        return: "8.5433",
        issue_number: "2608/182",
        auction_date: "12/06/2025",
        value_dated: "16/06/2025",
    },
    {
        value: "t_bill_364",
        label: "364-Day Treasury Bill",
        return: "9.9985",
        issue_number: "2562/364",
        auction_date: "12/06/2025",
        value_dated: "16/06/2025",
    },
];

export const reits = [
    { name: "ACORN D-REIT", price: 26.7 },
    { name: "i-REIT", price: 22.9 },
    { name: "ILAM FAHARI", price: 11 },
    { name: "LAPTRUST IMARA IREIT", price: 20 },
];

export const shares = [
    { ticker: "SCOM - Safaricom PLC", price: 27.95 },
    { ticker: "EQTY - Equity Group Holdings Plc", price: 60.50 },
    { ticker: "EABL - East African Breweries PLC", price: 235.75 },
    { ticker: "KCB - KCB Group PLC", price: 59.75 },
    { ticker: "SCBK - Standard Chartered Bank Kenya Ltd", price: 287.00 },
    { ticker: "ABSA - Absa Bank Kenya PLC", price: 22.00 },
    { ticker: "COOP - Co-operative Bank of Kenya Ltd", price: 21.00 },
    { ticker: "NCBA - NCBA Group PLC", price: 79.25 },
    { ticker: "SBIC - Stanbic Holdings Plc", price: 193.75 },
    { ticker: "IMH - I&M Group PLC", price: 45.15 },
    { ticker: "KEGN - KenGen PLC", price: 8.02 },
    { ticker: "BAT - British American Tobacco Kenya plc", price: 449.00 },
    { ticker: "BKG - BK Group PLC", price: 39.65 },
    { ticker: "KQ - Kenya Airways Plc", price: 3.68 },
    { ticker: "UMME - Umeme Ltd", price: 6.80 },
    { ticker: "DTK - Diamond Trust Bank Kenya Ltd", price: 115.0 },
    { ticker: "BAMB - Bamburi Cement PLC", price: 54.0 },
    { ticker: "BRIT - Britam Holdings Plc", price: 8.76 },
    { ticker: "KPLC - Kenya Power & Lighting Co Ltd", price: 11.50 },
    { ticker: "JUB - Jubilee Holdings Ltd", price: 326.75 },
    { ticker: "TOTL - TotalEnergies Marketing Kenya PLC", price: 36.30 },
    { ticker: "HFCK - HF Group PLC", price: 9.50 },
    { ticker: "KNRE - Kenya Reinsurance Corp. Ltd", price: 2.86 },
    { ticker: "KUKZ - Kakuzi PLC", price: 414.50 },
    { ticker: "CTUM - Centum Investment Co Plc", price: 12.80 },
    { ticker: "CIC - CIC Insurance Group PLC", price: 4.49 },
    { ticker: "CRWN - Crown Paints Kenya PLC", price: 51.50 },
    { ticker: "CARB - Carbacid Investments Plc", price: 27.10 },
    { ticker: "LBTY - Liberty Kenya Holdings Plc", price: 10.25 },
    { ticker: "TPSE - TPS Eastern Africa Plc", price: 14.90 },
    { ticker: "WTK - Williamson Tea Kenya Plc", price: 150.00 },
    { ticker: "SASN - Sasini PLC", price: 18.45 },
    { ticker: "PORT - East African Portland Cement PLC", price: 75.50 },
    { ticker: "NBV - Nairobi Business Ventures PLC", price: 1.45 },
    { ticker: "KAPC - Kapchorua Tea Kenya PLC", price: 210.25 },
    { ticker: "CGEN - Car & General (Kenya) Plc", price: 51.50 },
    { ticker: "UNGA - Unga Group Plc", price: 23.55 },
    { ticker: "SCAN - WPP Scangroup Plc", price: 2.66 },
    { ticker: "SMER - Sameer Africa PLC", price: 13.45 },
    { ticker: "SLAM - Sanlam Kenya Plc", price: 8.16 },
    { ticker: "LKL - Longhorn Publishers PLC", price: 1.45 },
    { ticker: "AMAC - Africa Mega Agricorp PLC", price: 72.00 },
    { ticker: "EGAD - Eaagads Ltd", price: 17.40 },
    { ticker: "HAFR - Home Afrika Ltd", price: 1.06 },
    { ticker: "FTGH - FTG Holdings Ltd", price: 1.59 },
    { ticker: "EVRD - Eveready East Africa PLC", price: 1.32 },
    { ticker: "OCH - Olympia Capital Holdings Ltd", price: 7.02 },
    { ticker: "UCHM - Uchumi Supermarkets Ltd", price: 1.59 },
];

export const insurances = [
    {
        name: "Britam Holdings PLC",
        policies: [
            "Life insurance",
            "Health insurance",
            "General insurance (motor, home, travel)",
            "Investment-linked plans",
            "Retirement planning",
        ],
        value: "britam_holdings_plc",
    },
    {
        name: "Jubilee Insurance",
        policies: [
            "Life insurance",
            "Health insurance",
            "General insurance",
            "Asset management solutions",
            "Comprehensive health plans",
            "Personal accident covers",
            "Pension schemes",
        ],
        value: "jubilee_insurance",
    },
    {
        name: "CIC Insurance Group",
        policies: [
            "Life insurance",
            "General insurance",
            "Health insurance",
            "Micro insurance",
            "Solutions for cooperative societies and SMEs",
        ],
        value: "cic_insurance_group",
    },
    {
        name: "APA Insurance",
        policies: [
            "General insurance (motor, property, marine)",
            "Health insurance",
            "Life insurance",
            "Corporate and individual health plans",
        ],
        value: "apa_insurance",
    },
    {
        name: "Old Mutual Kenya",
        policies: [
            "Life insurance",
            "General insurance",
            "Investment plans",
            "Retirement solutions",
            "Education savings plans",
            "Pension schemes",
        ],
        value: "old_mutual_kenya",
    },
    {
        name: "Sanlam Kenya",
        policies: [
            "Life insurance",
            "General insurance",
            "Investment solutions",
            "Retirement planning",
            "Investment-linked insurance products",
        ],
        value: "sanlam_kenya",
    },
    {
        name: "ICEA LION Group",
        policies: [
            "Life insurance",
            "General insurance",
            "Health insurance",
            "Investment products",
            "Retirement schemes",
            "Unit trust investments",
        ],
        value: "icea_lion_group",
    },
    {
        name: "Pioneer Assurance",
        policies: [
            "Life insurance",
            "General insurance",
            "Pension plans",
            "Education policies",
            "Savings and last expense cover",
            "School Fees Plus Policy",
            "Family Care",
        ],
        value: "pioneer_assurance",
    },
    {
        name: "Liberty Life Assurance Kenya",
        policies: [
            "Life insurance",
            "Pension plans",
            "Investment solutions",
            "Education savings",
            "Retirement planning",
        ],
        value: "liberty_life_assurance_kenya",
    },
    {
        name: "First Assurance Kenya (Absa Group)",
        policies: [
            "General insurance (motor, property)",
            "Medical insurance",
            "Group life insurance",
        ],
        value: "first_assurance_kenya",
    },
];
