name: Deploy Laravel Project on push
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo_mysql, fileinfo
          tools: composer:v2
          coverage: none
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build assets
        run: |
          npm ci
          npm run build
        
      - name: Install Dependencies
        run: |
          rm -rf vendor composer.lock
          composer install --no-dev --optimize-autoloader --no-interaction || exit 1
        
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          exclude: |
            .env
            .git
            .github
            node_modules
            
      - name: Execute migrations on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/zuriuhqx/zuritconsulting.com
            composer dump-autoload
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache